- README.md
Plus a little more introductory text.
Link to rendered version for easy review: https://github.com/helium/HIP/blob/f776fa83e23318283ebec2e867fe63394b59e8e4/README.md
Arguably the draft proposals shouldn't have a HIP# yet, like the one I marked "Draft (Abandoned)" Perhaps we include them in a separate "Drafts" section?
Doing this update helped clarify some of the overall HIP process for me too... here's my current understanding
* Draft: PR with `.md` file submitted, but not yet merged
* Discussion: PR merged; repo admins should open an issue for discussion, and probably update both README and the specific HIP's `.md` file to link to the discussion issue
* Accepted/Merged/Deployed more TBD but we should definitely do #27
> README updates, particularly fixing states of outstanding HIPs

- 0010-usage-based-data-transfer-rewards.md
Here's a proposal for a proportional reward scheme for data transfers based on conversations I've had with folks around the community.
Rendered view: https://github.com/helium/HIP/pull/31/files#diff-e355d9a98c1cc82cb2057ba677307e15
> Proportional reward scheme for data transfers

- 0010-remote-location-assert.md
- remote-location-assert.md
Since the GPS location assertion check will soon be enforced, more than 1500 hotspots will need to be adjusted in some way in order to have a good GPS fix and continue participating in Proof of Coverage (see current hotspot `gps_fix_quality` states below). For many hotspots, this will require updating the asserted location to accurately reflect the hotspot's latest location, which can currently only be done with physical access to the hotspot.
```
gps_fix_quality | count 
----------------+-------
good_fix        |  2275
no_fix          |  1090
bad_assert      |   514
```
This HIP proposes a new transaction, `assert_location_v2`, which will allow a hotspot's location to be asserted remotely without physical access to the hotspot.
> HIP(x): Remote Location Assert

- 0004-expensing-data-credits-for-lorawan.md
- README.md
Our current definition for how DCs are expensed for LoRaWAN traffic did not account for "empty" acknowledgement packets, ie: ACK frames that do not have FRMPayload or FOpts. I do not believe our intention was to make ACKs free, so this has been corrected.
In addition, article `0004` is renamed from the generic "data credits" to "expensing data credits for lorawan", as the article itself is not nearly as broad as the original title suggested.
> DC Expensing Amendment to Charge for ACK frames

- 0013-transfer-hotspot.md
- 0099-transfer-hotspot.md
- README.md
* PR #42
* Author: @mrallen1, @abhay 
* HIP Number: TBD
* Tracking issue: TBD
**Summary:** This proposal introduces a new type of transaction to the Helium blockchain called transfer_gateway_v1. This transaction will be an atomic transfer of an onboarded Hotspot / gateway from one owner to another. This transaction can have an optional amount of HNT associated.
**Rendered version:** https://github.com/helium/HIP/blob/9cf52310b532d98232d21de33449ce789c58ef10/0099-transfer-hotspot.md
> Propose Transfer Hotspot

- 0012-remote-location-assert.md
Removes reference to GPS fix, which no longer exists in the system. This feature remains useful without GPS fix requirement.
> Update HIP12: Remove references to GPS fix

- 0016-random-consensus-group-election.md
- 00XX-random-CG-election.md
Initial creation of a HIP to change CG election protocol to randomly elect CG members vs. using hotspots score which has been shown to be unreliable and easily gamed.
Rendered view: https://github.com/helium/HIP/blob/fcd14e14c94b0642ddff59cf8110d2ea8a9fd304/00XX-random-CG-election.md
> Draft HIP to randomly elect CG members

- 0016-random-consensus-group-election.md
Since we're using a random function to elect/deselect, we shouldn't bother calling it a score.
cc: @jamiew @PaulVMo
> Update HIP 16 to remove notion of a "CG score"

- 0020-hnt-max-supply.md
- README.md
Related to HIP20 #73 
I'm reposting the rationale I posted in [a comment on the above issue](https://github.com/helium/HIP/issues/73#issuecomment-730473527), for posterity: 
> I am pleased to formally recognize that rough consensus has been achieved on this proposal and I'll be marking it as approved, with the first halving date as-proposed for August 1st, 2020. On behalf of the community I'm also requesting the core development team begin any necessary engineering work.
>
> In unscientific Discord polling, HIP20 had 99% support. Those poll numbers also pretty accurately reflect what I've observed in conversations here, in Discord, and in private conversations with interested parties who do not follow the day-to-day of community governance.
>
> This proposal was circulated widely. Beyond …
> HIP20: mark as Approved

- 0019-third-party-manufacturers.md
Based on conversations with the community, there is a lot of interest in requiring manufacturers approved through this process to protect `swarm_keys` specifically.
The PR amends the HIP to specifically enumerate requirements they'd have to put into their applications
The relevant text (right now)
> Additionally, we want devices approved under this proposal to be reasonably secure and resistant to tampering. The original Helium hotspots used an ECC chip to house the  `swarm_key` using a secure ECC chip, which was significantly more secure than the external SD card and unencrypted file storage used by the current RAKspots. We propose that applicants are required to include:
>
> - Encrypted/locked-down firmware
> - Encrypted storage of the miner `swarm_key`, either via disk encryption or …
> HIP19: add hardware security requirements

- 0019-third-party-manufacturers.md
Diff: https://github.com/helium/HIP/pull/98/files
Rendered view: https://github.com/helium/HIP/blob/7129a3858dbe06ecb21a24b3436ab02c75416b34/0019-third-party-manufacturers.md
* Explicitly defers the details of a systen for actually issuing keys to manufacturer to a separate solution, through the HIP process or otherwise.
* Proposes the same HIP-style process for revoking manufacturer approval. Currently no way to remove hotspots from the network, and defers consideration
of that to a future proposal.
I believe that the two companies that have applied to be manufacturers should not be held in limbo just because we haven't finalized how they are going to get keys. I also don't think tracking keys on-chain is absolutely a firm requirement, since it could be quite involved.
> HIP19: more on key issuance and revocation

- 0019-third-party-manufacturers.md
- README.md
Following onto #87 
Via Discord discussion, informal polls, the most recent community calls, and private discussions with folks not represented in those other forums, the Helium community have expressed overwhelming support for approving this proposal and moving forward w/ evaluating the two current applicants, Nebra Ltd & SyncroB.it
Addressing the remaining concerns: 
* Helium Inc have indicated their support and willingness to accept onboarding keys from approved manufacturers, and developing a process by which the issuance of those keys can be made public. 
* The community & manufacturers have both agreed that it's OK to approve this proposal this system is still being developed
* Lastly, it is agreed that adding the ability to revoke existing keys should be addressed in a separate …
> HIP19: mark as approved

- README.md
Per conversations in Discord and informal polling, there is wide support for approving all 3 of **Nebra Ltd**, **SyncroB.it** and **RAK Wireless** as third-party manufacturers of Helium-compatible hotspots.
On behalf of the community I request that Helium Inc get in touch and arrange for ongoing key issuance. I expect more detail about the key-sharing process will be added to [HIP19](https://github.com/helium/HIP/issues/87) as the details are fleshed out.
> Mark Nebra, SyncroB.it & RAK as approved third-party manufacturers

- 0000-template.md
- 0027-cbrs-5g-support.md
Rendered view: https://github.com/helium/HIP/blob/4455cbfb575eefcf4ece4ad1a91c6b0a14d09f90/0000-template.md
> Support 5G on the Helium network

- 0027-cbrs-5g-support.md
It should be LoRaWAN not LoRaWan
> fix LoRaWAN typo

- README.md
Reposting my comment on their application PR: https://github.com/helium/HIP/pull/137#issuecomment-819696961
In recognition of:
I am pleased to memorialize community consensus for approving **HeNet/LongAP** as a third-party manufacturer of Helium-compatible hotspots by marking this proposal approved ✅
> Mark LongAP HIP19 application as approved

- 0029-multisig-addresses.md
- 0029-multisignature-keys.md
- README.md
Rendered: https://github.com/helium/HIP/blob/sk/multisig/0029-multisignature-keys.md
> HIP 29: M-of-N Multisig

- 00xx-safe-rf-metadata-side-channel.md
Author(s): @wavesoft, @dmamalis
Initial PR: #249 
Start Date: 2021-07-28
Category: Technical
Rendered view:
https://github.com/helium/HIP/blob/9ce376f2d18d973fb26aac44360f072cb6d86512/00xx-safe-rf-metadata-side-channel.md
Summary:
The goals of these changes are to:
Introduce a new side-channel from which RF meta-data can be collected, in a way that no sensitive information
can be disclosed to third parties.
> HIP00xx: Safe RF Meta-Data Side Channel 

- 0031-governance-by-token-burn.md
- 0031-governance-by-token-lock.md
- README.md
A rewrite of the existing HIP31. This proposal suggests on-chain governance voting for implementations of chain variables and protocol upgrades.
> Rewrite HIP31 with Token Lock rather than Token Burn mechanism

- 0028-consensus-reward-adjustments.md
- README.md
On behalf of the DeWi and broader Helium community, I'm happy to label this HIP as "community approved." 
This comes in recognition of:
- wide support from the community on multiple [community calls](https://dewi.org/community-calls)
- nearly unanimous support in Discord straw polling (though emoji data was lost to some Discord server gremlins)
- support (in principle) from members of the core development team
HIP author @PaulVMo has also written the first draft of actual code because he is awesome! That PR is [helium/blockchain-core#922](https://github.com/helium/blockchain-core/pull/922) and is undergoing review by the core development team. Please follow that issue for updates; when it is merged or rejected I'll try to update here.
Please note that community approval of a HIP and the …
> Mark HIP28 as approved

- 0036-blockheights-instead-of-time.md
- README.md
At the time of writing, most (if not all) blockchain variables and implementations are activated manually by the Helium team, requiring active intervention from the team and have a time-based activation. The active intervention can, for the greatest part, be avoided by enabling auto-activation of variables at certain blockheights. This has been the standard for most blockchain projects. One example is the bi-yearly halving of HNT rewards agreed to in HIP20 which should be integrated with blockheights rather than be defined by moment in time for its activation - and in the future, hopefully any change of blockchain variables can be defined that way.
This HIP does not contain a complete schedule for HIP20, but does contain all variables needed to properly create the schedule (last halving …
> HIP36 proposal: use blockheights instead of time

- 0019-third-party-manufacturers.md
Tried to preserve original language but point people to the new repository, which is the most up-to-date.
> Update HIP19 to link to new repository

- 0043-software-release-guidelines.md
- 0043-update-release-guidelines.md
Rendered view: 
https://github.com/helium/HIP/blob/59d64dfb7ea3f6c5ad02d667c11825eea39d2f7c/0043-update-release-guidelines.md
> HIP draft: guidelines for software releases

- 0049-max-eirp-adjustment.md
- README.md
This proposal suggests adopting a LoRaWAN subregion config for max EIRP limit which will allow individual countries within an RF region i.e. AS923 to define max EIRP limit based on each country’s local regulation instead of a single max EIRP limit across the entire AS923 as a result of PoCv11.
Hope to hear everyone's feedback! Thank you! :)
> HIP draft – LoRaWAN Sub-region Max EIRP Limit

- 0045-lorawan-frequency-plan-selection.md
- README.md
See my comments in https://github.com/helium/HIP/issues/311 re approval evidence and logic. Thank you!
_Originally posted by @jamiew in https://github.com/helium/HIP/issues/311#issuecomment-1032684671_
> There has been strong support for this proposal. The coredevs support it, the newly formed LoRaWAN committee supports it, it has 95%+ support in Discord straw polling, and there have no concerns raised either here or on the monthly community call, and it has been open for several months.
>
> I believe this proposal has passed our standard for rough consensus, and an on-chain temperature check or vote is not required.
>
> On behalf of the DeWi, the HIP Editors, and the wider Helium community, I am marking this proposal as approved, and request that the coredev team implement the necessary …
> Mark HIP45 doc as approved

- 0051-helium-dao.md
> HIP 51 revisions 2/23 Final Update

- 0055-validator-challenges.md
Corrects the number and title of the H3Dex HIP, and adds a space between 'HIP' and the number, matching the format of HIP 10 (with a space) further down in the document.
> Fix HIP 54 Reference and Formatting in HIP 55

- 0044-witness-decay.md
both figures were linking to focused-population-graph.png, but the first fig should be population-graph.png
> update population-graph link

- 0059-reduce-xor-filter-fees.md
[rendered](https://github.com/helium/HIP/blob/macpie/HIP-59/0059-reduce-xor-filter-fees.md)
> HIP-59: Reduce XOR filter fees

- 0053-mobile-dao.md
• Consistent use of 'subDAO'
• Typos
> HIP53: Typos/formatting

- 0070-scaling-helium.md
tl;dr
* Staked HNT continues to become veHNT with 6 month lockup
* Staked HNT in Cooldown becomes locked HNT with vesting matching remaining cooldown period
* No change to any unstaked HNT.
**Reasoning:** We've received an overwhelming amount of feedback from validators / stakers that the reduction in cooldown, although preferable to some parties is the ecosystem, is an overall negative change in this HIP. Specifically, it introduces a major economic change to the network inside of a technical upgrade. Instead of introducing the cooldown, we've consulted with experts in the Solana ecosystem to implement the migration of stakes in cooldown to vesting tokens. This will enable anyone to unstake, if they choose to, at anytime and still be able to complete their cooldown after the L1 migration …
> HIP 70: Remove cooldown reduction

- 0074-mobile-poc-modeled-coverage-rewards.md
Looks much more intimidating that it really is.
- Grammar corrections/smoothing
- Capitalization of network entities and other ecosystem proper nouns to align with docs 
- Rewrite Passive Voice to Active Voice
- Update figure and table numbers, made bold for visibility 
- Correct numbered list of all 1's
- Disambiguate "coverage points" from "reward points" 
- Table formatting to markdown conventions
- KaTex formatting on example rewards equations
- Swap italics for `code` styling on equation components in explainer text
- Replace “This HIP” with “HIP-74”
> HIP-74 Cleanup

- 0076-linear-lockup-curve.md
HIP-70 specifies the duration of the automatic lockup period applied to an HNT validator stake that has not completed cooldown at transition, and is therefore rolled over into a locked HNT position, as the “minimum lockup period”, which is defined in HIP-51 as 6 months. This HIP revises the minimum lockup period to zero. Thus we now clarify that the validator rollover lockup period is still 6 months.
#560
> clarify 6-month lockup for validator rollover

- 0079-mobile-poc-mappers-rewards.md
A comprehensive editorial pass on HIP-79. A few issues still remain:
- usage of "Hotspot" vs "Radio"
- missing link for Mobile PoC Working Group discussion
> HIP-79 editorial

- 0081-minimum-onboarding-fee.md
This PR explicitly defines some of the remaining ambiguities:
- The actually burned DC is used for $A$ in the DAO Utility Score
- Not required to onboard to every subDAO the hardware is capable of
- Payer of onboarding fees is explicitly left to the subDAO
- Make explicit what devices need to be onboarded
- Show the progression of the dynamic onboarding fee over time
> Explicitly define some ambiguities

- .prettierrc
no more forced wraps! (if using vscode and prettier)
> comment out prose wrap and print width in prettier config

- 0000-oracle-hex-boosting.md
- 0103-oracle-hex-boosting.md
This Helium Improvement Proposal (HIP) discusses how Oracle Boosting rewards are calculated and creates a new Footfall Oracle, which incentives deployments in areas that have heavy footfall traffic.
> HIP 103: MOBILE Oracle Hex Boosting

- 0102-helium-educational-lns.md
This is trivial but worth fixing to support text search for the keyword "disallow".
> Fix misprint in HIP-102 "disllowment" -> "disallowment"

- 0105-modification-of-mobile-subdao-hex-limits.md
We just learned that they way HIP 85 was implemented, Wi-Fi and CBRS are treated equally, whereas the limit per res12 hex is 3. So I had to make changes in this HIP clarifying that was the case.
> HIP 105: Updates

- 0000-hex-boosting-by-deployment.md
- 0109-hex-boosting-by-deployment.md
This Helium Improvement Proposal (HIP) allows Service Providers to specify what types of deployments their hex boosting can be applied to (i.e. CBRS vs Wi-Fi).
> HIP 109: Hex Boosting by Deployment

- 0112-scaling-iot-location-assert-fees.md
- xxxx-scaling-iot-location-assert-fees.md
This HIP proposes allowing one (1) free IOT assertion per rolling 365 day period, including the initial assertion. Any additional assertions conducted within the 365 day rolling period will be required to pay a $10 fee in IOT burn.
> HIP 112: Scaling IOT Hotspot Assert Fees

- 0117-mntd-mobile-hotspot-vendor.md
Re-submitting from personal account as edits by maintainers are not possible on PRs from organisations.
> HIP 117: Add MNTD. as a Hotspot Vendor to the Helium MOBILE subNetwork

- 0116-oui-additional-address-space-reshuffle.md
adjusted hip to reflect community feedback.
- keeping block sizes at 8 but reducing the cost from $800 to $100. 
- Purchased costs when actioned to be via burning IOT.
> HIP 116: adjust hip to reflect community feedback

- 0114-incentive-escrow-fund-for-subscriber-referrals.md
The key differences are to:
1. Not track changes over long periods of time and potentially across wallets. It’s not really manageable.  So no burns at the end of 12 months. This does remove a burn opportunity which needs discussion
2. Note that ALL referral rewards allocated for a given reward epoch are emitted to eligible referrals. This may not match all referral program types but also follows the typical early adopter rush employed in existing hotspot and subscriber phases
> HIP 114 adjustments based on technical review and discussion

- 0119-closing-gaming-loopholes-within-the-mobile-network.md
- xxxx-closing-gaming-loopholes-within-the-mobile-network.md
This Helium Improvement Proposal (HIP) proposes closing gaming loopholes to help prevent gaming within the MOBILE network.
> HIP 119: Closing Gaming Loopholes Within the MOBILE Network

- 0000-Temporary-Anti-Gaming-Measures-For-Boosted-Hexes.md
- 0125-temporary-anti-gaming-measures-for-boosted-hexes.md
This proposal outlines measures to invalidate boosted hex rewards for mobile hotspots that engage in malicious activity to earn boosted hex rewards on the MOBILE network.
> HIP 125: Temporary Anti-Gaming Measures For Boosted Hexes

- 0122-amend-service-provider-hex-boosting.md
This HIP aims to do three (3) things to amend HIP-84 Service Provider Hex Boosting.
1. Create a dedicated Service Provider Hex Boosting Rewards bucket. This will be 10% within the entire ecosystem. This will be taken out of the current 20% PoC bucket, making the regular PoC bucket 10% of the ecosystem after. The 40% data bucket that bleeds into PoC if unused will remain untouched.
2. Reduce the minimum time for Service Provider Hex Boosting to 3 months.
3. Limit FUTURE boost creation to a maximum of 10x.
> HIP 122: Updates

- 0123-redefining-data-only-onboarding-and-assertion-fees.md
- Elaborates on motivation and background
- Sets onboarding and assertion costs to $0.50 and $0.50, respectively
- Eliminates the 30-epoch threshold for free onboarding
For approval by @Ducktatorrr and the broader IoT Working Group
> HIP 123: Updates

- 0122-amend-service-provider-hex-boosting.md
This HIP aims to do three things to amend HIP-84 Service Provider Hex Boosting. It creates a dedicated Service Provider Hex Boosting emissions funding category. It reduces the minimum time for Service Provider Hex Boosting to 3 months and finally limits future boost creation to a maximum of 10x rewards.
- The dedicated Service Provider Hex Boosting Rewards bucket will be limited to a maximum of 10% of all future emissions in the MOBILE network and will be taken out of the current Proof-of-Coverage category (reduced from 20% to a minimum of 10%). Any of the 10% not used by Service Provider Hex Boosting is returned to the Proof-of-Coverage bucket. 
- The minimum time for Service Provider Hex Boosting is reduced to 3 months from 6 months to allow more flexibility of boosting to hexes that …
> 0122-amend-service-provider-hex-boosting.md

- 0122-amend-service-provider-hex-boosting.md
Planner will indeed need to reflect that boost rewards could be lower than the multiplier indicates, if it doesn’t already. This is not a HIP detail though, so removing it here for clarity
> remove planner reference

- 0123-redefining-data-only-onboarding-and-assertion-fees.md
Given that the success of this HIP is predicated on qualitative improvements ("more" data on chain and "more" data-only hotspots leading to a better coverage maps), I'm removing the somewhat vague success metric.
> HIP 123: Remove success metric

- 0128-energy-subnetwork.md
What's changed:
- Removed the network growth pool.
- Onboarding fee 10 USD in DC.
- Vendors can issue coupons for onboarding fees
- Added 100M carve out for the beta testers, taken from the 1B pool from Operations Fund for liquidity.
- Removed free DER onboarding for existing hotspots (because of anti-gaming threshold).
- Added a note for reasoning of DC fees (in the end).
- Removal of the network rate for data.
> HIP 128: Onboarding fees and vendor coupon

- 0132-scaling-mobile-mappers.md
- 0xxx-scaling-mobile-mappers.md
Adding new HIP for scaling mobile mappers per last week's discussion at the mobile working group.
> HIP 132: Scaling MOBILE Mappers
